- name: Add Jenkins repository
  yum_repository:
    name: Jenkins-stable
    description:  Jenkins Stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
- name: Install Java
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: latest

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest

- name: Make sure the groovy init scripts are setup
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    mode: 0755
    owner: jenkins
    group: jenkins

- name: Bypass - jenkins.install.InstallUtil.lastExecVersion
  copy: src=/var/lib/jenkins/jenkins.install.UpgradeWizard.state
        dest=/var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
        owner=jenkins
        group=jenkins
        remote_src=True

- name: Bypass - initialAdminPassword
  shell: mv /var/lib/jenkins/secrets/initialAdminPassword /root || echo "Nothing to move"
  notify:
    - restart jenkins

- name: Set up security settings
  template:
    src: 'basic-security.groovy'
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
